<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Elemini</title>\n";
echo "    <link rel=\"stylesheet\" href=\"../css/Elemini.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"../css/style.css\">\n";
echo "</head>\n";
echo "<body>\n";
include 'menubar.php';
echo "    <div class=\"backgroundImage\"> \n";
echo "        <div class=\"title\">\n";
echo "            <h3 id=\"topTitle\">UVSASE presents</h3>\n";
echo "            <h1 class=\"eleminiTitle\">ELEMINI</h1>\n";
echo "            <h3 id=\"bottomTitle\">Unearth your potential</h3>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "\n";
echo "    <br><br><br><br><br><br>\n";
echo "    <div class=\"centerLine\">\n";
echo "        <div class=\"descriptionSection\">\n";
echo "            <h1 id=\"title\">What is Element?</h1>\n";
echo "            <p>\n";
echo "                The Element Conference is UVSASE’S premier \n";
echo "                leadership conference aimed to provide \n";
echo "                professional and personal development for \n";
echo "                aspiring young leaders of the Vietnamese-American \n";
echo "                community.  Our programs, spanning across three days \n";
echo "                and two nights, are designed to provide participants \n";
echo "                with the knowledge to excel in their leadership \n";
echo "                roles and careers.  Through an immersive learning \n";
echo "                environment, this conference will provide the hands-on \n";
echo "                experience for attendees to learn the skills needed to \n";
echo "                be successful in all their endeavors.\n";
echo "            </p>\n";
echo "            <br><br>\n";
echo "            <h1 id=\"title\">Theme?</h1>\n";
echo "            <p>\n";
echo "                Do you feel like you are stuck in the dirt? \n";
echo "                Many of us were put under amount of stress \n";
echo "                during the last year where different areas \n";
echo "                of our lives were impacted. Whether it was \n";
echo "                adjusting to changed pace of school and/or \n";
echo "                work, you may have struggled through it. \n";
echo "                You may not know what kind of potential you \n";
echo "                hold that can be developed. You know you have \n";
echo "                a lot of potential to grow but don’t have the \n";
echo "                right tools? Everyone is unique in their own \n";
echo "                way and there no concrete path to be successful \n";
echo "                leader. Imagine that everyone is seed that has \n";
echo "                the potential to develop and grow. Not everyone \n";
echo "                grows exactly the same whether as a potato or \n";
echo "                tomato BUT eventually finds their own niche in \n";
echo "                the garden. That means everyone may utilize \n";
echo "                different tools to get where they want to be \n";
echo "                as a leader or in a career.\n";
echo "            </p>\n";
echo "        </div>\n";
echo "        <br><br><br><br><br><br>\n";
echo "\n";
echo "        <div class=\"row\">\n";
echo "            <div class=\"halfColumn dateInfo\">\n";
echo "                <h1 id=\"title\">June 26 - 27</h1>\n";
echo "                <p>\n";
echo "                    ALL VIRTUAL<br>\n";
echo "                    <ul>\n";
echo "                        <li>description</li>\n";
echo "                        <li>description</li>\n";
echo "                        <li>description</li>\n";
echo "                    </ul>\n";
echo "                </p> \n";
echo "            </div>\n";
echo "            <div class=\"halfColumn\">\n";
echo "                <button type=\"button\" class=\"registerButton\">Register Now!</button>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "\n";
echo "        <br><br><br><br><br><br>\n";
echo "        <div class=\"row\">\n";
echo "            <h1 id=\"title\">Workshops and Speakers</h1>\n";
echo "            <div class=\"fourthColumn tab\">\n";
echo "                <img src=\"orange.jpg\" width=250px height= 300px>\n";
echo "                <h3>Speaker Name</h3>\n";
echo "                <h4>Workshop Title</h4>\n";
echo "            </div>\n";
echo "            <div class=\"fourthColumn\">\n";
echo "                <img src=\"apple.jpg\" width=250px height= 300px>\n";
echo "                <h3>Speaker Name</h3>\n";
echo "                <h4>Workshop Title</h4>\n";
echo "            </div>\n";
echo "            <div class=\"fourthColumn\">\n";
echo "                <img src=\"cherry.jpg\" width=250px height= 300px>\n";
echo "                <h3>Speaker Name</h3>\n";
echo "                <h4>Workshop Title</h4>\n";
echo "            </div>\n";
echo "            <div class=\"fourthColumn\">\n";
echo "                <img src=\"peach.jpg\" width=250px height= 300px>\n";
echo "                <h3>Speaker Name</h3>\n";
echo "                <h4>Workshop Title</h4>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </div>\n";
echo "</body>\n";
echo "</html>\n";

?>