<?php
echo "<!doctype html>\n";
echo "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1\" crossorigin=\"anonymous\">\n";
echo "<link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>\n";
echo "<html lang=\"en\">\n";
echo "    <head>\n";
echo "        <link rel=\"stylesheet\" href=\"../css/style.css\">\n";
echo "        <meta charset=\"utf-8\">\n";
echo "        <title>Elemini Leaderboard</title>\n";
echo "        \n";
echo "        <link rel=\"shortcut icon\" href=\"favicon.ico\">\n";
echo "        <script src = \"Registration and Login Check.js\"></script>\n";
echo "    </head>\n";
echo "    <body>\n";
include 'menubar.php';
/*echo "        <ul>\n";
echo "            <li><a href=\"#home\">\n";
echo "                <img id=\"logo\" src=\"../images/uvsase_darkbg_logomark-e1503005399285.png\" alt=\"UVSASE Logo\"width=25>\n";
echo "            </a></li>\n";
echo "            <li><a href=\"#home\">ELEMINI</a></li>\n";
echo "            <li style=\"float:right\"><a class=\"active\" href=\"sign_up\">Register</a></li>\n";
echo "            <li style=\"float:right\"><a  href=\"login.html\">Login</a></li>\n";
echo "        </ul>\n";*/
echo "    \n";
echo "        <h1 style=\"text-align:center;color:bisque; margin-top:3%;\">\n";
echo "            <img id=\"logo\" src=\"../images/cherry.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            <img id=\"logo\" src=\"../images/orange.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            <img id=\"logo\" src=\"../images/apple.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            <img id=\"logo\" src=\"../images/peach.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            <img id=\"logo\" src=\"../images/pear.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            Leaderboard\n";
echo "            <img id=\"logo\" src=\"../images/pear.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            <img id=\"logo\" src=\"../images/peach.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            <img id=\"logo\" src=\"../images/apple.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            <img id=\"logo\" src=\"../images/orange.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "            <img id=\"logo\" src=\"../images/cherry.png\" alt=\"UVSASE Logo\"width=100>\n";
echo "        </h1>\n";
echo "        \n";
echo "        <table>\n";
echo "        <tr class=\"titles\">\n";
echo "            \n";
echo "            <th>Family</th>\n";
echo "            <th>Score</th>\n";
echo "        </tr>\n";
echo "        <tr>\n";
echo "            <td><img id=\"logo\" src=\"../images/peach.png\" alt=\"UVSASE Logo\"width=150>Peaches</td>\n";
echo "            <td>100</td>\n";
echo "            \n";
echo "        </tr>\n";
echo "        <tr>\n";
echo "            \n";
echo "            <td><img id=\"logo\" src=\"../images/pear.png\" alt=\"UVSASE Logo\"width=150>Pears</td>\n";
echo "            <td>150</td>\n";
echo "            \n";
echo "        </tr>\n";
echo "        <tr>\n";
echo "            <td><img id=\"logo\" src=\"../images/orange.png\" alt=\"UVSASE Logo\"width=150>Oranges</td>\n";
echo "            <td>135</td>\n";
echo "            \n";
echo "        </tr>\n";
echo "        <tr>\n";
echo "            <td><img id=\"logo\" src=\"../images/cherry.png\" alt=\"UVSASE Logo\"width=150>Cherries</td>\n";
echo "            <td>140</td>\n";
echo "            \n";
echo "        </tr>\n";
echo "        <tr>\n";
echo "            <td><img id=\"logo\" src=\"../images/apple.png\" alt=\"UVSASE Logo\"width=150>Apples</td>\n";
echo "            <td>105</td>\n";
echo "            \n";
echo "        </tr>\n";
echo "        \n";
echo "        </table>\n";
echo "        \n";
echo "        \n";
echo "          \n";
echo "    </body>\n";
echo "</html>";


?>