<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\n";
echo "    integrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\" crossorigin=\"anonymous\">\n";
echo "    <link rel=\"stylesheet\" href=\"../css/workshops.css\">\n";
echo "    <link rel=\"stylesheet\" href=\"../css/style.css\">\n";
echo "\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
echo "    <title>Document</title>\n";
echo "</head>\n";
echo "<body>\n";
include 'menubar.php';
/*echo "<!-- Current code is an outline of the webpage, it is not complete -->\n";
echo "\n";
echo "<!-- nav bar by Shreya -->\n";
echo "  <ul id=\"header\">\n";
echo "      <li><a href=\"#home\">\n";
echo "          <img id=\"logo\" src=\"../images/uvsase_darkbg_logomark-e1503005399285.png\" alt=\"UVSASE Logo\"width=25>\n";
echo "      </a></li>\n";
echo "      <li><a href=\"#home\">ELEMINI</a></li>\n";
echo "      <li style=\"float:right\"><a  href=\"sign_in.html\">Register</a></li>\n";
echo "      <li style=\"float:right\"><a class=\"active\" href=\"login.html\">Login</a></li>\n";
echo "  </ul>\n";*/
echo "\n";
echo "    <!-- Title -->\n";
echo "    <h1 class=\"pageHeader\">Elemini 2021 Workshops</h1>\n";
echo "\n";
echo "    <!-- Insturctions Section -->\n";
echo "    <div class=\"card instructions\">\n";
echo "        <div class=\"card-header\">\n";
echo "          Instructions\n";
echo "        </div>\n";
echo "        <div class=\"card-body\">\n";
echo "            <ul>\n";
echo "                <li>You will see below that there are 4 different options for each workshop time slot. <br>Please select <b>one workshop</b> for each timeslot</li>\n";
echo "                <li>The workshop timeslots are as follows:<br>    Section #1: Saturday, Nov. 21st @ 10:40AM - 11:55AM ET<br>    Section #2: Saturday, Nov. 21st @ 10:40AM - 11:55AM ET<br>    Section #3: Saturday, Nov. 21st @ 10:40AM - 11:55AM ET</li>\n";
echo "                <li><b>Please choose your workshop carefully, as you will not be able to change your workshop on this portal if you regret your choice.</b></li>\n";
echo "            </ul>          \n";
echo "        </div>\n";
echo "    </div>\n";
echo "\n";
echo "    <!-- First Section -->\n";
echo "    <h3 class=\"sectionHeader\">Workshops in Section #1</h3>\n";
echo "    <div class=\"card-deck section\">\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This card has supporting text below as a natural lead-in to additional content.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "            <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "            <div class=\"card-body\">\n";
echo "              <h5 class=\"card-title\">Card title</h5>\n";
echo "              <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>\n";
echo "            </div>\n";
echo "            <div class=\"card-footer\">\n";
echo "              <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "      </div>\n";
echo "      <!-- End First Section -->\n";
echo "\n";
echo "      <!-- Second Section -->\n";
echo "      <h3 class=\"sectionHeader\">Workshops in Section #2</h3>\n";
echo "      <div class=\"card-deck section\">\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This card has supporting text below as a natural lead-in to additional content.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "            <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "            <div class=\"card-body\">\n";
echo "              <h5 class=\"card-title\">Card title</h5>\n";
echo "              <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>\n";
echo "            </div>\n";
echo "            <div class=\"card-footer\">\n";
echo "              <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "      </div>\n";
echo "      <!-- End Second Section -->\n";
echo "\n";
echo "      <!-- Third Section -->\n";
echo "      <h3 class=\"sectionHeader\">Workshops in Section #3</h3>\n";
echo "      <div class=\"card-deck section last\">\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This card has supporting text below as a natural lead-in to additional content.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "          <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "          <div class=\"card-body\">\n";
echo "            <h5 class=\"card-title\">Card title</h5>\n";
echo "            <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>\n";
echo "          </div>\n";
echo "          <div class=\"card-footer\">\n";
echo "            <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "          </div>\n";
echo "        </div>\n";
echo "        <div class=\"card\">\n";
echo "            <img class=\"card-img-top\" src=\"../images/card.svg\" alt=\"Card image cap\">\n";
echo "            <div class=\"card-body\">\n";
echo "              <h5 class=\"card-title\">Card title</h5>\n";
echo "              <p class=\"card-text\">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>\n";
echo "            </div>\n";
echo "            <div class=\"card-footer\">\n";
echo "              <small class=\"text-muted\"><button type=\"button\" class=\"btn btn-outline-success\">Register</button></small>\n";
echo "            </div>\n";
echo "          </div>\n";
echo "      </div>\n";
echo "      <!-- End Third Section -->\n";
echo "</body>\n";
echo "</html>";

?>